name: build-linux-container
on:
  push:
    branches:
      - master

jobs:
  ubuntu-20:
    runs-on: ubuntu-20.04
    steps:
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: actions/checkout@v2
      - name: Build
        run: |
          docker login 
          cd ./build/docker/dotnet6-paddle
          docker build . -t sdflysha/dotnet6-paddle:2.3.0-ubuntu20
          docker push sdflysha/dotnet6-paddle:2.3.0-ubuntu20