name: main
env:
  tag: 2.3.0-ubuntu20
on:
  push:
    branches:
      - master
  workflow_dispatch:
  

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Restore depedencies
        run: dotnet restore
      - name: Build code
        run: dotnet build -c Release --no-restore
      - name: Test
        run: dotnet test -c Release --no-build --verbosity normal
  linux-ubuntu:
    runs-on: ubuntu-latest
    container: sdflysha/dotnet6sdk-paddle:${{ env.tag }}
    steps:
      - uses: actions/checkout@v3
      - name: Restore depedencies
        run: dotnet restore
      - name: Build code
        run: dotnet build -c Release --no-restore
      - name: Test
        run: dotnet test -c Release --no-build --verbosity normal