name: build-linux-container
on:
  push:
    branches:
      - master

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build code
        run: |
          dotnet build -c Release
      - name: Test
        run: |
          dotnet test -c Release
  linux-ubuntu:
    runs-on: ubuntu-latest
    env:
      tag: 2.3.0-ubuntu20
    steps:
      - uses: actions/checkout@v2
      - name: Build code
        run: |
          dotnet build -c Release
      #- uses: docker/login-action@v2
      #  with:
      #    username: ${{ secrets.DOCKER_USERNAME }}
      #    password: ${{ secrets.DOCKER_TOKEN }}
      #- name: Build runtime container
      #  run: |
      #    cd ${{ github.workspace }}/build/docker/dotnet6-paddle
      #    docker build . -t sdflysha/dotnet6-paddle:$tag
      #    docker push sdflysha/dotnet6-paddle:$tag
      #- name: Build sdk container
      #  run: |
      #    cd ${{ github.workspace }}/build/docker/dotnet6sdk-paddle
      #    docker build . -t sdflysha/dotnet6sdk-paddle:$tag
      #    docker push sdflysha/dotnet6sdk-paddle:$tag
      - uses: kohlerdominik/docker-run-action@v1
        with:
          image: sdflysha/dotnet6sdk-paddle:${{ env.tag }}
          volumes: ${{ github.workspace }}:/workspace
          run: |
            cd /workspace
            dotnet test -c Release